proxy:
    title: "ShinyProxy Hello"
    port: 8080
    authentication: simple
    admin-groups: [admins]

    container-backend: docker
    docker:
        url: "unix:///var/run/docker.sock"
        internal-networking: true
        container-network: sp-net
        container-wait-time: 60000

    users:
        - name: jack
          password: password
          groups: [admins]

    specs:
        - id: hello
          display-name: "Hello World"
          description: "Démo shinyproxy::run_01_hello()"
          container-image: openanalytics/shinyproxy-demo
          container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
          container-name: hello-app # <- hostname stable
          container-network: sp-net # <- le même réseau que ShinyProxy
